'use client'

import { useState } from 'react'
import { Bell, KeyRound, Save, ShieldCheck, UserRound } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Switch } from '@/components/ui/switch'

export default function SettingsPage() { const [saved, setSaved] = useState(false); return <div className="flex max-w-4xl flex-col gap-6"><div><p className="text-xs uppercase tracking-[0.18em] text-muted-foreground">Account</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Settings</h1><p className="mt-1 text-sm text-muted-foreground">Manage your workspace, profile, and execution preferences.</p></div><Card><CardHeader><CardTitle className="flex items-center gap-2 text-sm"><UserRound className="size-4 text-muted-foreground" /> Profile</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor="name">Full name</Label><Input id="name" defaultValue="Bala Sanjeev" /></div><div className="grid gap-2"><Label htmlFor="email">Email address</Label><Input id="email" defaultValue="bala@mcpier.dev" /></div></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2 text-sm"><ShieldCheck className="size-4 text-muted-foreground" /> Execution defaults</CardTitle></CardHeader><CardContent className="divide-y divide-border"><div className="flex items-center justify-between py-3"><div><p className="text-sm">Require approval for write actions</p><p className="mt-1 text-xs text-muted-foreground">Pause before an MCP changes external data.</p></div><Switch defaultChecked /></div><div className="flex items-center justify-between py-3"><div><p className="text-sm">Retain sandbox artifacts</p><p className="mt-1 text-xs text-muted-foreground">Keep files available after task completion.</p></div><Switch defaultChecked /></div></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2 text-sm"><Bell className="size-4 text-muted-foreground" /> Notifications</CardTitle></CardHeader><CardContent className="divide-y divide-border"><div className="flex items-center justify-between py-3"><div><p className="text-sm">Task completion alerts</p><p className="mt-1 text-xs text-muted-foreground">Receive an alert when an execution finishes.</p></div><Switch defaultChecked /></div><div className="flex items-center justify-between py-3"><div><p className="text-sm">Failure alerts</p><p className="mt-1 text-xs text-muted-foreground">Notify me when an execution needs attention.</p></div><Switch defaultChecked /></div></CardContent></Card><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-xs text-muted-foreground"><KeyRound className="size-3.5" /> API keys are managed securely per workspace.</div><Button onClick={() => { setSaved(true); setTimeout(() => setSaved(false), 2200) }}><Save data-icon="inline-start" />{saved ? 'Saved' : 'Save changes'}</Button></div></div> }

