'use client'

import { useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Check, Code2, GitBranch, Plus, Sparkles } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'

const types = ['Blank Project', 'Web Application', 'Node.js', 'Python', 'React', 'Next.js', 'FastAPI', 'MCP Server', 'Docker', 'Other']
export default function NewCodewriteProject() {
  const [type, setType] = useState('MCP Server'); const [name, setName] = useState('customer-support')
  return <div className="mx-auto flex max-w-4xl flex-col gap-8"><div><Link href="/dashboard/codewrite" className="flex items-center gap-2 text-xs text-muted-foreground hover:text-foreground"><ArrowLeft className="size-3.5" /> Back to Codewrite</Link><h1 className="mt-6 text-2xl font-semibold tracking-tight">Create project</h1><p className="mt-1 text-sm text-muted-foreground">Start with a template or bring your own idea into a sandboxed workspace.</p></div><div className="grid gap-8 lg:grid-cols-[1fr_280px]"><section className="rounded-lg border border-border bg-card p-6"><Label>Project name</Label><Input value={name} onChange={e => setName(e.target.value)} className="mt-2" placeholder="my-project" /><Label className="mt-6 block">Choose a project type</Label><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{types.map(item => <button key={item} onClick={() => setType(item)} className={`flex items-center gap-2 rounded-md border p-3 text-left text-xs transition-colors ${type === item ? 'border-primary bg-primary/10 text-foreground' : 'border-border text-muted-foreground hover:bg-muted'}`}>{type === item ? <Check className="size-3.5 text-primary" /> : <Code2 className="size-3.5" />}{item}</button>)}</div><div className="mt-7 grid gap-4 sm:grid-cols-2"><div><Label>Runtime</Label><Input className="mt-2" value="Node.js 22" readOnly /></div><div><Label>Language</Label><Input className="mt-2" value={type === 'Python' || type === 'FastAPI' ? 'Python' : 'TypeScript'} readOnly /></div></div><div className="mt-6 space-y-3 text-sm"><label className="flex items-center gap-3"><input type="checkbox" defaultChecked className="accent-primary" /> Initialize Git repository</label><label className="flex items-center gap-3"><input type="checkbox" defaultChecked className="accent-primary" /> Use MCPier sandbox</label></div><Button className="mt-8 w-full" render={<Link href={`/dashboard/codewrite/${name || 'untitled-project'}`} />}><Plus /> Create project</Button></section><aside className="rounded-lg border border-border bg-card p-5"><div className="flex items-center gap-2 text-sm font-medium"><Sparkles className="size-4 text-primary" /> Create with AI</div><p className="mt-2 text-xs leading-5 text-muted-foreground">Describe an app and MCPier will generate the initial project structure for you.</p><textarea className="mt-4 min-h-28 w-full resize-none rounded-md border border-border bg-background p-3 text-xs outline-none focus:border-primary" placeholder="A FastAPI backend with PostgreSQL authentication..." /><Button variant="outline" className="mt-3 w-full"><Sparkles /> Generate project</Button><div className="mt-7 border-t border-border pt-4"><p className="flex items-center gap-2 text-xs font-medium"><GitBranch className="size-3.5" /> Git repository</p><p className="mt-2 text-[11px] leading-5 text-muted-foreground">You can import or connect a repository after creating your workspace.</p></div></aside></div></div>
}
