'use client'

import { use, useMemo, useState } from 'react'
import Link from 'next/link'
import { Activity, Bot, ChevronDown, Code2, Files, GitBranch, Play, Plus, Search, Settings2, Sparkles, Terminal, X, Zap } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'

const initialFiles: [string, boolean][] = [
  ['src', true], ['  index.ts', false], ['  tools.ts', false], ['tests', true], ['  index.test.ts', false], ['package.json', false], ['README.md', false], ['.env.example', false]
]
const snippets: Record<string, string> = {
  'index.ts': `import { Server } from "@modelcontextprotocol/sdk/server"\nimport { tools } from "./tools"\n\nconst server = new Server({\n  name: "customer-support",\n  version: "1.0.0"\n})\n\nfor (const tool of tools) {\n  server.tool(tool.name, tool.handler)\n}\n\nserver.listen()`,
  'tools.ts': `export const tools = [\n  {\n    name: "lookup_order",\n    description: "Find an order by ID",\n    handler: async ({ orderId }: { orderId: string }) => ({\n      content: [{ type: "text", text: \`Order \${orderId} is in transit.\` }]\n    })\n  }\n]`,
}

export default function CodewriteEditorPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params)
  const [active, setActive] = useState('index.ts')
  const [openTabs, setOpenTabs] = useState(['index.ts', 'tools.ts', 'package.json'])
  const [code, setCode] = useState(snippets['index.ts'])
  const [panel, setPanel] = useState<'terminal' | 'problems' | 'output'>('terminal')
  const [running, setRunning] = useState(false)
  const [ai, setAi] = useState(true)
  const [newFile, setNewFile] = useState(false)
  const [files, setFiles] = useState<[string, boolean][]>(initialFiles)
  const [query, setQuery] = useState('')
  const visibleFiles = useMemo(() => files.filter(([name]) => name.toLowerCase().includes(query.toLowerCase())), [files, query])
  const openFile = (name: string) => { const clean = name.trim(); setActive(clean); setCode(snippets[clean] ?? `// ${clean}\n\n`); if (!openTabs.includes(clean)) setOpenTabs([...openTabs, clean]) }
  return <div className="-m-4 flex h-[calc(100vh-4rem)] min-h-[680px] flex-col overflow-hidden border border-border bg-background lg:-m-6">
    <header className="flex h-12 shrink-0 items-center gap-3 border-b border-border bg-card px-4">
      <Link href="/dashboard/codewrite" className="text-xs text-muted-foreground hover:text-foreground">Codewrite</Link><span className="text-muted-foreground">/</span><span className="text-sm font-medium">{id}</span><Badge variant="secondary" className="ml-1">MCP project</Badge><div className="ml-auto flex items-center gap-2"><Button size="sm" variant="ghost"><GitBranch className="size-3.5" /> main <ChevronDown className="size-3" /></Button><Button size="sm" variant="outline"><Settings2 className="size-3.5" /> Project settings</Button><Button size="sm" onClick={() => { setRunning(true); setPanel('output'); setTimeout(() => setRunning(false), 1500) }}><Play className="size-3.5" /> {running ? 'Running' : 'Run'}</Button></div>
    </header>
    <div className="flex min-h-0 flex-1">
      <nav className="hidden w-12 shrink-0 flex-col items-center gap-5 border-r border-border bg-card py-4 text-muted-foreground lg:flex"><Files className="size-4 text-foreground" /><Search className="size-4" /><GitBranch className="size-4" /><Activity className="size-4" /><Zap className="size-4" /><div className="mt-auto"><Settings2 className="size-4" /></div></nav>
      <aside className="hidden w-60 shrink-0 border-r border-border bg-card md:block"><div className="flex items-center justify-between px-4 py-3"><span className="text-[11px] font-semibold uppercase tracking-widest">Explorer</span><div className="flex gap-2 text-muted-foreground"><Plus onClick={() => setNewFile(true)} className="size-4 cursor-pointer hover:text-foreground" /><span className="text-xs">•••</span></div></div><div className="px-3 pb-3"><Input value={query} onChange={e => setQuery(e.target.value)} placeholder="Filter files" className="h-7 text-xs" /></div><div className="px-2 text-xs">{visibleFiles.map(([name, folder]) => <button key={name} onClick={() => !folder && openFile(name)} className={`flex w-full items-center gap-2 rounded px-2 py-1.5 text-left ${name.trim() === active ? 'bg-primary/10 text-primary' : 'text-muted-foreground hover:bg-muted hover:text-foreground'}`}>{folder ? <ChevronDown className="size-3" /> : <Code2 className="size-3" />}<span>{name}</span>{!folder && name.includes('tools') && <span className="ml-auto text-[10px] text-amber-400">M</span>}</button>)}</div>{newFile && <div className="mx-3 mt-3 flex gap-1"><Input autoFocus placeholder="filename.ext" className="h-7 text-xs" onKeyDown={e => { if (e.key === 'Enter' && e.currentTarget.value) { setFiles([...files, [e.currentTarget.value, false]]); setNewFile(false); openFile(e.currentTarget.value) } }} /><X className="mt-1.5 size-3 cursor-pointer" onClick={() => setNewFile(false)} /></div>}<div className="mt-8 border-t border-border p-3"><p className="mb-2 text-[10px] font-semibold uppercase tracking-widest text-muted-foreground">Source Control</p><p className="text-xs text-muted-foreground">2 changes</p><p className="mt-2 text-xs text-amber-400">M tools.ts</p><p className="text-xs text-emerald-400">A index.test.ts</p></div></aside>
      <main className="flex min-w-0 flex-1 flex-col"><div className="flex h-10 shrink-0 items-center overflow-x-auto border-b border-border bg-card">{openTabs.map(tab => <button key={tab} onClick={() => openFile(tab)} className={`flex h-full shrink-0 items-center gap-3 border-r border-border px-4 text-xs ${tab === active ? 'border-t-2 border-t-primary bg-background text-foreground' : 'text-muted-foreground'}`}>{tab}{tab === 'tools.ts' && <span className="text-amber-400">●</span>}<X className="size-3" onClick={e => { e.stopPropagation(); setOpenTabs(openTabs.filter(t => t !== tab)) }} /></button>)}<button className="px-3 text-muted-foreground"><Plus className="size-3" /></button></div><div className="flex h-9 shrink-0 items-center gap-3 border-b border-border px-4 text-xs text-muted-foreground"><span>src</span><span>/</span><span className="text-foreground">{active}</span><span className="ml-auto font-mono">TypeScript React</span></div><div className="relative min-h-0 flex-1 overflow-auto bg-background"><textarea value={code} onChange={e => setCode(e.target.value)} spellCheck={false} className="absolute inset-0 h-full w-full resize-none border-0 bg-transparent p-5 pl-14 font-mono text-[13px] leading-6 text-foreground outline-none" />{<div className="pointer-events-none absolute left-0 top-0 w-12 select-none p-5 pr-2 text-right font-mono text-[12px] leading-6 text-muted-foreground/50">{code.split('\n').map((_, i) => <div key={i}>{i + 1}</div>)}</div>}</div><div className="flex h-9 shrink-0 items-center gap-5 border-t border-border bg-card px-4 text-[11px] text-muted-foreground"><span>Ln 8, Col 1</span><span>Spaces: 2</span><span>UTF-8</span><span className="text-amber-400">⚠ 2</span><span className="text-red-400">× 1</span><span className="ml-auto">TypeScript</span><span className="text-emerald-400">Sandbox Connected</span></div></main>
      <aside className={`${ai ? 'w-72' : 'w-0'} hidden shrink-0 overflow-hidden border-l border-border bg-card transition-all xl:block`}><div className="flex h-10 items-center justify-between border-b border-border px-4"><span className="flex items-center gap-2 text-xs font-semibold"><Sparkles className="size-3.5 text-primary" /> MCPier AI</span><X className="size-3 cursor-pointer text-muted-foreground" onClick={() => setAi(false)} /></div><div className="p-4"><p className="text-xs leading-5 text-muted-foreground">Ask about <span className="text-foreground">{active}</span> or your project structure.</p><div className="mt-4 flex flex-wrap gap-2">{['Explain', 'Fix', 'Refactor', 'Generate tests'].map(x => <button key={x} className="rounded border border-border px-2 py-1 text-[11px] text-muted-foreground hover:border-primary hover:text-primary">{x}</button>)}</div><div className="mt-6 rounded-md border border-border bg-background p-3"><div className="flex items-center gap-2 text-xs"><Bot className="size-3.5 text-primary" /> Ready to help</div><p className="mt-2 text-[11px] leading-5 text-muted-foreground">I can explain code, inspect errors, or propose a safe change without overwriting your work.</p></div><div className="mt-4 flex gap-2"><Input placeholder="Ask about your code..." className="h-8 text-xs" /><Button size="icon" className="size-8"><Zap className="size-3.5" /></Button></div></div><div className="border-t border-border p-4"><p className="text-[10px] font-semibold uppercase tracking-widest text-muted-foreground">MCP Inspector</p><p className="mt-3 text-xs font-medium">Customer Support</p><div className="mt-2 flex items-center gap-2 text-[11px] text-emerald-400"><span className="size-1.5 rounded-full bg-emerald-400" /> Running</div><div className="mt-4 space-y-2 text-[11px] text-muted-foreground"><p>Tools <span className="float-right text-foreground">8</span></p><p>Resources <span className="float-right text-foreground">3</span></p><p>Prompts <span className="float-right text-foreground">2</span></p></div></div></aside>
    </div>
    <section className="h-44 shrink-0 border-t border-border bg-card"><div className="flex h-9 items-center gap-5 border-b border-border px-4 text-[11px] font-semibold uppercase tracking-wider"><button onClick={() => setPanel('terminal')} className={panel === 'terminal' ? 'border-b-2 border-primary py-2 text-foreground' : 'text-muted-foreground'}><Terminal className="mr-1 inline size-3" /> Terminal</button><button onClick={() => setPanel('output')} className={panel === 'output' ? 'border-b-2 border-primary py-2 text-foreground' : 'text-muted-foreground'}>Output</button><button onClick={() => setPanel('problems')} className={panel === 'problems' ? 'border-b-2 border-primary py-2 text-foreground' : 'text-muted-foreground'}>Problems <span className="ml-1 text-red-400">3</span></button><span className="ml-auto text-muted-foreground">+ New Terminal</span></div><div className="p-4 font-mono text-xs leading-6 text-muted-foreground">{panel === 'terminal' ? <><p><span className="text-primary">$</span> npm install</p><p>added 242 packages in 2.4s</p><p><span className="text-primary">$</span> npm run dev</p><p className="text-emerald-400">Sandbox process running on port 3000</p></> : panel === 'output' ? <><p className="text-emerald-400">✓ Application running</p><p>Preview available at http://localhost:3000</p></> : <><p className="text-red-400">error TS2339: Property 'token' does not exist on type Request</p><p className="text-amber-400">warning: unused variable 'config'</p></>}</div></section>
  </div>
}
