export interface McpField {
  name: string
  label: string
  type: 'text' | 'password' | 'select' | 'checkbox' | 'textarea'
  placeholder?: string
  required?: boolean
  options?: string[]
  description?: string
  defaultValue?: string | boolean
}

export interface McpCatalogItem {
  id: string
  name: string
  category: string
  group: 'Cloud & Infrastructure' | 'Databases & Storage' | 'DevOps & Tooling' | 'Productivity & Apps' | 'Observability & Monitoring'
  description: string
  iconKey: string
  brandColor: string
  detailsSummary: string
  fields: McpField[]
}

export const MCP_CATALOG: McpCatalogItem[] = [
  {
    id: 'github',
    name: 'GitHub MCP',
    category: 'Source Control',
    group: 'DevOps & Tooling',
    description: 'Official GitHub MCP Server providing repository, issues, PRs, and code search capabilities directly via GitHub Copilot.',
    iconKey: 'github',
    brandColor: '#24292e',
    detailsSummary: 'Official GitHub MCP endpoint (https://api.githubcopilot.com/mcp/) with GitHub Personal Access Token (PAT)',
    fields: [
      {
        name: 'url',
        label: 'Server Endpoint URL',
        type: 'text',
        defaultValue: 'https://api.githubcopilot.com/mcp/',
        required: true,
        description: 'Official GitHub MCP HTTP JSON-RPC endpoint.',
      },
      {
        name: 'token',
        label: 'GitHub Personal Access Token (PAT)',
        type: 'password',
        placeholder: 'ghp_xxxxxxxxxxxxxxxxxxxx or github_pat_xxxx',
        required: true,
        description: 'Requires repo, user, and read:org permissions.',
      },
      {
        name: 'transport',
        label: 'Transport Protocol',
        type: 'select',
        options: ['http', 'sse'],
        defaultValue: 'http',
        required: true,
      },
    ],
  },
  {
    id: 'filesystem',
    name: 'Filesystem MCP',
    category: 'Local & Remote Storage',
    group: 'DevOps & Tooling',
    description: 'Read, write, search, and manage files and directory trees securely within specified path bounds.',
    iconKey: 'filesystem',
    brandColor: '#4f46e5',
    detailsSummary: 'Local/remote server command or URL, allowed directory/path, transport',
    fields: [
      {
        name: 'allowed_path',
        label: 'Allowed Root Directory / Path',
        type: 'text',
        placeholder: '/workspace or C:\\Projects\\workspace',
        required: true,
        description: 'Restricts MCP file access exclusively to this folder path.',
      },
      {
        name: 'server_command',
        label: 'Server Command or Endpoint URL',
        type: 'text',
        placeholder: 'npx -y @modelcontextprotocol/server-filesystem /workspace',
        defaultValue: 'npx -y @modelcontextprotocol/server-filesystem',
        required: true,
      },
      {
        name: 'transport',
        label: 'Transport Protocol',
        type: 'select',
        options: ['stdio', 'sse (Server-Sent Events)', 'http'],
        defaultValue: 'stdio',
        required: true,
      },
    ],
  },
  {
    id: 'playwright',
    name: 'Playwright MCP',
    category: 'Testing & Browser Automation',
    group: 'DevOps & Tooling',
    description: 'Automate web browsing, headless interaction, scraping, DOM evaluation, and end-to-end testing.',
    iconKey: 'playwright',
    brandColor: '#2ead33',
    detailsSummary: 'MCP server command/URL, browser choice, optional headless mode, optional browser profile/storage state',
    fields: [
      {
        name: 'server_command',
        label: 'Server Command or URL',
        type: 'text',
        placeholder: 'npx -y @modelcontextprotocol/server-playwright',
        defaultValue: 'npx -y @modelcontextprotocol/server-playwright',
        required: true,
      },
      {
        name: 'browser',
        label: 'Browser Choice',
        type: 'select',
        options: ['Chromium', 'Firefox', 'WebKit'],
        defaultValue: 'Chromium',
        required: true,
      },
      {
        name: 'headless',
        label: 'Headless Mode',
        type: 'checkbox',
        defaultValue: true,
        description: 'Run browser in headless background mode without graphical window.',
      },
      {
        name: 'storage_state',
        label: 'Browser Profile / Storage State Path (Optional)',
        type: 'text',
        placeholder: './storage-state.json',
        required: false,
      },
    ],
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL MCP',
    category: 'Relational Database',
    group: 'Databases & Storage',
    description: 'Executes parameterized SQL queries, inspects schema definitions, and manages table migrations.',
    iconKey: 'postgresql',
    brandColor: '#336791',
    detailsSummary: 'PostgreSQL host, port, database, username, password, SSL settings, connection string',
    fields: [
      {
        name: 'connection_string',
        label: 'PostgreSQL Connection String (or fill individual fields below)',
        type: 'password',
        placeholder: 'postgresql://postgres:password@localhost:5432/mcp_db',
        required: false,
      },
      {
        name: 'host',
        label: 'Host',
        type: 'text',
        placeholder: 'localhost or db.example.com',
        defaultValue: 'localhost',
        required: false,
      },
      {
        name: 'port',
        label: 'Port',
        type: 'text',
        placeholder: '5432',
        defaultValue: '5432',
        required: false,
      },
      {
        name: 'database',
        label: 'Database Name',
        type: 'text',
        placeholder: 'production_db',
        required: true,
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        placeholder: 'postgres',
        defaultValue: 'postgres',
        required: true,
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        placeholder: '••••••••••••',
        required: true,
      },
      {
        name: 'ssl_mode',
        label: 'SSL Settings',
        type: 'select',
        options: ['disable', 'require', 'verify-ca', 'verify-full'],
        defaultValue: 'require',
        required: true,
      },
    ],
  },
  {
    id: 'docker',
    name: 'Docker MCP',
    category: 'Containers',
    group: 'DevOps & Tooling',
    description: 'Build, inspect, run containers, stream logs, and publish images to private or public registries.',
    iconKey: 'docker',
    brandColor: '#2496ed',
    detailsSummary: 'Docker daemon/socket access, Docker host if remote, authentication if using a remote registry',
    fields: [
      {
        name: 'socket_path',
        label: 'Docker Daemon / Socket Path',
        type: 'text',
        placeholder: '/var/run/docker.sock or //./pipe/docker_engine',
        defaultValue: '/var/run/docker.sock',
        required: true,
      },
      {
        name: 'docker_host',
        label: 'Remote Docker Host (Optional)',
        type: 'text',
        placeholder: 'tcp://192.168.1.100:2375',
        required: false,
      },
      {
        name: 'registry_url',
        label: 'Registry URL (Optional)',
        type: 'text',
        placeholder: 'docker.io or ghcr.io',
        required: false,
      },
      {
        name: 'registry_token',
        label: 'Registry Auth Token (Optional)',
        type: 'password',
        placeholder: 'dckr_pat_...',
        required: false,
      },
    ],
  },
  {
    id: 'aws',
    name: 'AWS MCP',
    category: 'Cloud Infrastructure',
    group: 'Cloud & Infrastructure',
    description: 'Provision compute, manage S3 storage, execute Lambda functions, and query CloudWatch logs.',
    iconKey: 'aws',
    brandColor: '#ff9900',
    detailsSummary: 'AWS authentication, region, IAM permissions/role, optionally AWS account/profile/credentials',
    fields: [
      {
        name: 'auth_mode',
        label: 'AWS Authentication Mode',
        type: 'select',
        options: ['IAM Access Keys', 'IAM Role ARN (AssumeRole)', 'Environment / Instance Profile'],
        defaultValue: 'IAM Access Keys',
        required: true,
      },
      {
        name: 'region',
        label: 'AWS Region',
        type: 'text',
        placeholder: 'us-east-1',
        defaultValue: 'us-east-1',
        required: true,
      },
      {
        name: 'access_key_id',
        label: 'AWS Access Key ID',
        type: 'text',
        placeholder: 'AKIAIOSFODNN7EXAMPLE',
        required: true,
      },
      {
        name: 'secret_access_key',
        label: 'AWS Secret Access Key',
        type: 'password',
        placeholder: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY',
        required: true,
      },
      {
        name: 'session_token',
        label: 'Session Token (Optional)',
        type: 'password',
        placeholder: 'AQoDYXdzEJr...',
        required: false,
      },
      {
        name: 'role_arn',
        label: 'IAM Role ARN (Optional)',
        type: 'text',
        placeholder: 'arn:aws:iam::123456789012:role/McpExecutionRole',
        required: false,
      },
    ],
  },
  {
    id: 'godot',
    name: 'Godot MCP',
    category: 'Game Engine',
    group: 'DevOps & Tooling',
    description: 'Creates and modifies 2D/3D scenes, attaches GDScripts, imports assets, and runs game previews.',
    iconKey: 'godot',
    brandColor: '#478cbf',
    detailsSummary: 'Godot project path, Godot executable/path, MCP server URL or local command, transport',
    fields: [
      {
        name: 'project_path',
        label: 'Godot Project Path',
        type: 'text',
        placeholder: 'D:/Projects/MyGodotGame',
        required: true,
        description: 'Directory containing the project.godot configuration file.',
      },
      {
        name: 'executable_path',
        label: 'Godot Executable Path',
        type: 'text',
        placeholder: 'godot or C:\\Program Files\\Godot\\Godot_v4.exe',
        defaultValue: 'godot',
        required: true,
      },
      {
        name: 'server_url',
        label: 'MCP Server URL or Local Command',
        type: 'text',
        placeholder: 'npx -y godot-mcp-server or ws://localhost:9090',
        defaultValue: 'npx -y godot-mcp-server',
        required: true,
      },
      {
        name: 'transport',
        label: 'Transport Protocol',
        type: 'select',
        options: ['stdio', 'websocket', 'http'],
        defaultValue: 'stdio',
        required: true,
      },
    ],
  },
  {
    id: 'slack',
    name: 'Slack MCP',
    category: 'Communication',
    group: 'Productivity & Apps',
    description: 'Interact with channels, send messages, read conversation threads, and upload files.',
    iconKey: 'slack',
    brandColor: '#4a154b',
    detailsSummary: 'OAuth authorization or Slack credentials/token, workspace/team authorization, required scopes',
    fields: [
      {
        name: 'auth_mode',
        label: 'Authorization Type',
        type: 'select',
        options: ['Bot Token (xoxb-...)', 'OAuth Authorization'],
        defaultValue: 'Bot Token (xoxb-...)',
        required: true,
      },
      {
        name: 'bot_token',
        label: 'Slack Bot User Token',
        type: 'password',
        placeholder: 'xoxb-your-slack-bot-token',
        required: true,
      },
      {
        name: 'team_id',
        label: 'Workspace / Team ID (Optional)',
        type: 'text',
        placeholder: 'T0123456789',
        required: false,
      },
      {
        name: 'scopes',
        label: 'Required Scopes',
        type: 'text',
        placeholder: 'channels:read,chat:write,files:write',
        defaultValue: 'channels:read,chat:write,files:write',
        required: false,
      },
    ],
  },
  {
    id: 'gdrive',
    name: 'Google Drive MCP',
    category: 'Cloud Storage & Docs',
    group: 'Productivity & Apps',
    description: 'Search documents, read spreadsheets, upload assets, and manage shared drive folders.',
    iconKey: 'gdrive',
    brandColor: '#4285f4',
    detailsSummary: 'Google OAuth, Google account authorization, client/app configuration where required, Drive scopes',
    fields: [
      {
        name: 'auth_mode',
        label: 'Google Account Authorization',
        type: 'select',
        options: ['Google OAuth 2.0', 'Service Account JSON Key'],
        defaultValue: 'Google OAuth 2.0',
        required: true,
      },
      {
        name: 'client_id',
        label: 'Google OAuth Client ID',
        type: 'text',
        placeholder: '1234567890-abc.apps.googleusercontent.com',
        required: true,
      },
      {
        name: 'client_secret',
        label: 'Client Secret',
        type: 'password',
        placeholder: 'GOCSPX-xxxxxxxxxxxxxxxx',
        required: true,
      },
      {
        name: 'scopes',
        label: 'Drive Scopes',
        type: 'select',
        options: ['drive.readonly (Read-only access)', 'drive.file (App-created files)', 'drive (Full drive access)'],
        defaultValue: 'drive.readonly (Read-only access)',
        required: true,
      },
    ],
  },
  {
    id: 'gitlab',
    name: 'GitLab MCP',
    category: 'DevOps & Git',
    group: 'DevOps & Tooling',
    description: 'Repository operations, CI/CD pipeline triggers, merge requests, and issue management.',
    iconKey: 'gitlab',
    brandColor: '#fc6d26',
    detailsSummary: 'GitLab OAuth authorization or access token, GitLab URL for self-managed instances',
    fields: [
      {
        name: 'gitlab_url',
        label: 'GitLab Instance URL',
        type: 'text',
        placeholder: 'https://gitlab.com or https://gitlab.mycorp.internal',
        defaultValue: 'https://gitlab.com',
        required: true,
      },
      {
        name: 'access_token',
        label: 'GitLab Personal Access Token',
        type: 'password',
        placeholder: 'glpat-xxxxxxxxxxxxxxxxxxxx',
        required: true,
        description: 'Requires api, read_repository, write_repository scopes.',
      },
    ],
  },
  {
    id: 'mongodb',
    name: 'MongoDB MCP',
    category: 'Document Database',
    group: 'Databases & Storage',
    description: 'Query BSON documents, perform aggregations, inspect collections, and manage Atlas clusters.',
    iconKey: 'mongodb',
    brandColor: '#13aa52',
    detailsSummary: 'MongoDB/Atlas connection string, optionally Atlas API client ID + secret, read-only mode',
    fields: [
      {
        name: 'connection_string',
        label: 'MongoDB / Atlas Connection String',
        type: 'password',
        placeholder: 'mongodb+srv://admin:pass@cluster0.abc.mongodb.net/dbname?retryWrites=true',
        required: true,
      },
      {
        name: 'atlas_client_id',
        label: 'Atlas API Public Key / Client ID (Optional)',
        type: 'text',
        placeholder: 'pub_xxxxxxxx',
        required: false,
      },
      {
        name: 'atlas_secret',
        label: 'Atlas API Private Key / Secret (Optional)',
        type: 'password',
        placeholder: '••••••••••••••••••••••••',
        required: false,
      },
      {
        name: 'read_only',
        label: 'Read-Only Mode',
        type: 'checkbox',
        defaultValue: false,
        description: 'Prevent write/delete operations against the database.',
      },
    ],
  },
  {
    id: 'redis',
    name: 'Redis MCP',
    category: 'In-Memory Database',
    group: 'Databases & Storage',
    description: 'Key-value operations, cache invalidation, pub/sub streams, hash manipulation, and latency telemetry.',
    iconKey: 'redis',
    brandColor: '#dc382d',
    detailsSummary: 'Redis URL/host, port, username, password, TLS/SSL settings, database number',
    fields: [
      {
        name: 'redis_url',
        label: 'Redis Host / URI',
        type: 'text',
        placeholder: 'localhost or redis://default:pass@redis.domain.com:6379',
        defaultValue: 'localhost',
        required: true,
      },
      {
        name: 'port',
        label: 'Port',
        type: 'text',
        placeholder: '6379',
        defaultValue: '6379',
        required: true,
      },
      {
        name: 'username',
        label: 'Username (ACL / Optional)',
        type: 'text',
        placeholder: 'default',
        required: false,
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        placeholder: '••••••••••••',
        required: false,
      },
      {
        name: 'db_number',
        label: 'Database Index',
        type: 'text',
        placeholder: '0',
        defaultValue: '0',
        required: true,
      },
      {
        name: 'tls_enabled',
        label: 'Enable TLS/SSL Encryption',
        type: 'checkbox',
        defaultValue: false,
      },
    ],
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes MCP',
    category: 'Container Orchestration',
    group: 'Cloud & Infrastructure',
    description: 'Manage pods, deployments, services, ingress routing, namespace manifests, and cluster logs.',
    iconKey: 'kubernetes',
    brandColor: '#326ce5',
    detailsSummary: 'Kubernetes API server/configuration, kubeconfig or cluster credentials, namespace/context, permissions',
    fields: [
      {
        name: 'auth_mode',
        label: 'Configuration Source',
        type: 'select',
        options: ['Kubeconfig File / Content', 'API Server URL + Bearer Token', 'In-Cluster Service Account'],
        defaultValue: 'Kubeconfig File / Content',
        required: true,
      },
      {
        name: 'kubeconfig',
        label: 'Kubeconfig Path or Raw YAML',
        type: 'textarea',
        placeholder: '~/.kube/config or paste kubeconfig YAML here',
        required: true,
      },
      {
        name: 'context',
        label: 'Cluster Context (Optional)',
        type: 'text',
        placeholder: 'minikube or gke_project_zone_cluster',
        required: false,
      },
      {
        name: 'namespace',
        label: 'Default Namespace',
        type: 'text',
        placeholder: 'default',
        defaultValue: 'default',
        required: true,
      },
    ],
  },
  {
    id: 'azure',
    name: 'Azure MCP',
    category: 'Cloud Platform',
    group: 'Cloud & Infrastructure',
    description: 'Provision Azure VMs, App Services, manage Blob Storage, and orchestrate Azure Resource Manager.',
    iconKey: 'azure',
    brandColor: '#0089d6',
    detailsSummary: 'Azure account/subscription, Microsoft Entra authentication, tenant/subscription context and required RBAC',
    fields: [
      {
        name: 'tenant_id',
        label: 'Microsoft Entra Tenant ID',
        type: 'text',
        placeholder: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        required: true,
      },
      {
        name: 'subscription_id',
        label: 'Azure Subscription ID',
        type: 'text',
        placeholder: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        required: true,
      },
      {
        name: 'client_id',
        label: 'App Registration Client ID',
        type: 'text',
        placeholder: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        required: true,
      },
      {
        name: 'client_secret',
        label: 'Client Secret',
        type: 'password',
        placeholder: '••••••••••••••••••••••••',
        required: true,
      },
      {
        name: 'resource_group',
        label: 'Default Resource Group (Optional)',
        type: 'text',
        placeholder: 'rg-production-eastus',
        required: false,
      },
    ],
  },
  {
    id: 'gcp',
    name: 'Google Cloud MCP',
    category: 'Cloud Platform',
    group: 'Cloud & Infrastructure',
    description: 'Manage Cloud Run services, Google Compute Engine, Cloud Storage buckets, and BigQuery analytics.',
    iconKey: 'gcp',
    brandColor: '#ea4335',
    detailsSummary: 'Google Cloud authentication, project ID, region/location where relevant, service-account/user credentials',
    fields: [
      {
        name: 'project_id',
        label: 'GCP Project ID',
        type: 'text',
        placeholder: 'my-gcp-project-123456',
        required: true,
      },
      {
        name: 'region',
        label: 'Region / Location',
        type: 'text',
        placeholder: 'us-central1',
        defaultValue: 'us-central1',
        required: true,
      },
      {
        name: 'auth_mode',
        label: 'Authentication Mode',
        type: 'select',
        options: ['Service Account JSON Key', 'Application Default Credentials (ADC)'],
        defaultValue: 'Service Account JSON Key',
        required: true,
      },
      {
        name: 'service_account_json',
        label: 'Service Account Key (JSON)',
        type: 'textarea',
        placeholder: '{\n  "type": "service_account",\n  "project_id": "...",\n  "private_key": "..."\n}',
        required: true,
      },
    ],
  },
  {
    id: 'notion',
    name: 'Notion MCP',
    category: 'Knowledge & Docs',
    group: 'Productivity & Apps',
    description: 'Query database tables, create and read workspace pages, append blocks, and sync team knowledge.',
    iconKey: 'notion',
    brandColor: '#000000',
    detailsSummary: 'OAuth authorization or Notion integration token, workspace/page access',
    fields: [
      {
        name: 'auth_mode',
        label: 'Authorization Type',
        type: 'select',
        options: ['Internal Integration Secret (secret_...)', 'OAuth Authorization'],
        defaultValue: 'Internal Integration Secret (secret_...)',
        required: true,
      },
      {
        name: 'integration_token',
        label: 'Notion Integration Secret',
        type: 'password',
        placeholder: 'secret_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        required: true,
      },
      {
        name: 'workspace_name',
        label: 'Workspace / Page Access Name (Optional)',
        type: 'text',
        placeholder: 'Engineering Workspace',
        required: false,
      },
    ],
  },
  {
    id: 'linear',
    name: 'Linear MCP',
    category: 'Issue Tracking',
    group: 'Productivity & Apps',
    description: 'Sync tickets, create issues, search backlog items, update status cycles, and link git PRs.',
    iconKey: 'linear',
    brandColor: '#5e6ad2',
    detailsSummary: 'OAuth or API key, workspace/team authorization, required permissions',
    fields: [
      {
        name: 'auth_mode',
        label: 'Authentication Mode',
        type: 'select',
        options: ['Linear API Key (lin_api_...)', 'OAuth Authorization'],
        defaultValue: 'Linear API Key (lin_api_...)',
        required: true,
      },
      {
        name: 'api_key',
        label: 'Linear Personal API Key',
        type: 'password',
        placeholder: 'lin_api_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        required: true,
      },
      {
        name: 'team_key',
        label: 'Default Team Key (Optional)',
        type: 'text',
        placeholder: 'ENG or PROD',
        required: false,
      },
    ],
  },
  {
    id: 'jira',
    name: 'Jira MCP',
    category: 'Enterprise Project Management',
    group: 'Productivity & Apps',
    description: 'Manage sprints, create Jira issues, update workflow statuses, and sync release roadmaps.',
    iconKey: 'jira',
    brandColor: '#0052cc',
    detailsSummary: 'Atlassian account authorization, OAuth or API token depending on implementation, Jira site URL',
    fields: [
      {
        name: 'jira_url',
        label: 'Jira Instance URL',
        type: 'text',
        placeholder: 'https://mycompany.atlassian.net',
        required: true,
      },
      {
        name: 'email',
        label: 'Atlassian Account Email',
        type: 'text',
        placeholder: 'developer@mycompany.com',
        required: true,
      },
      {
        name: 'api_token',
        label: 'Atlassian API Token',
        type: 'password',
        placeholder: '••••••••••••••••••••••••',
        required: true,
      },
      {
        name: 'project_key',
        label: 'Default Project Key (Optional)',
        type: 'text',
        placeholder: 'KAN or SCRUM',
        required: false,
      },
    ],
  },
  {
    id: 'sentry',
    name: 'Sentry MCP',
    category: 'Error Tracking & Performance',
    group: 'Observability & Monitoring',
    description: 'Query unresolved exceptions, inspect stack traces, analyze release health, and manage issue alerts.',
    iconKey: 'sentry',
    brandColor: '#362d59',
    detailsSummary: 'Sentry organization/project, authentication token/OAuth, required scopes',
    fields: [
      {
        name: 'sentry_url',
        label: 'Sentry Instance URL',
        type: 'text',
        placeholder: 'https://sentry.io',
        defaultValue: 'https://sentry.io',
        required: true,
      },
      {
        name: 'auth_token',
        label: 'Sentry User / Org Auth Token',
        type: 'password',
        placeholder: 'sntrys_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        required: true,
        description: 'Requires event:read, org:read, project:read scopes.',
      },
      {
        name: 'organization_slug',
        label: 'Organization Slug',
        type: 'text',
        placeholder: 'my-org',
        required: true,
      },
      {
        name: 'project_slug',
        label: 'Project Slug (Optional)',
        type: 'text',
        placeholder: 'frontend-service',
        required: false,
      },
    ],
  },
  {
    id: 'grafana',
    name: 'Grafana MCP',
    category: 'Dashboards & Metrics',
    group: 'Observability & Monitoring',
    description: 'Query dashboards, execute Prometheus/Loki queries, evaluate alerts, and stream telemetry panels.',
    iconKey: 'grafana',
    brandColor: '#f46800',
    detailsSummary: 'Grafana URL, service-account token or username/password, tool/RBAC permissions',
    fields: [
      {
        name: 'grafana_url',
        label: 'Grafana URL',
        type: 'text',
        placeholder: 'https://grafana.example.com',
        required: true,
      },
      {
        name: 'auth_mode',
        label: 'Authentication Method',
        type: 'select',
        options: ['Service Account Token (Recommended)', 'Basic Auth (Username/Password)'],
        defaultValue: 'Service Account Token (Recommended)',
        required: true,
      },
      {
        name: 'token',
        label: 'Service Account Token / API Key',
        type: 'password',
        placeholder: 'glsa_xxxxxxxxxxxxxxxxxxxx',
        required: true,
      },
    ],
  },
  {
    id: 'datadog',
    name: 'Datadog MCP',
    category: 'Cloud Telemetry & APM',
    group: 'Observability & Monitoring',
    description: 'Query APM traces, monitor alerts, inspect synthetics tests, and fetch host metrics.',
    iconKey: 'datadog',
    brandColor: '#632ca6',
    detailsSummary: 'Datadog site/region, API key, application key, required permissions',
    fields: [
      {
        name: 'datadog_site',
        label: 'Datadog Site / Region',
        type: 'select',
        options: ['datadoghq.com (US1)', 'us3.datadoghq.com (US3)', 'us5.datadoghq.com (US5)', 'datadoghq.eu (EU1)', 'ap1.datadoghq.com (AP1)'],
        defaultValue: 'datadoghq.com (US1)',
        required: true,
      },
      {
        name: 'api_key',
        label: 'Datadog API Key',
        type: 'password',
        placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        required: true,
      },
      {
        name: 'app_key',
        label: 'Datadog Application Key',
        type: 'password',
        placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        required: true,
      },
    ],
  },
]
